import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head";

const CommonLayout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>The Weighter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};

export default CommonLayout;
