import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Weighter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Contents */}
      <div className="flex w-full h-[88vh] items-center border-b-1 flex-col bg-white">
        <div className="flex w-full h-[35%] bg-banner justify-center items-center text-[30px] text-white">일상에서 찾아가는 건강</div>
      </div>

      {/* Footer */}
      <Footer />
    </div>
  );
}
